monitoring added in yml file

diff --git a/.github/workflows/data_collection.yml b/.github/workflows/data_collection.yml
--- a/.github/workflows/data_collection.yml
+++ b/.github/workflows/data_collection.yml
@@ -6,7 +6,7 @@ on:
   workflow_dispatch: # Allow manual trigger
 
 permissions:
-    contents: write
+  contents: write
 
 jobs:
   data-collection:
@@ -37,7 +37,7 @@ jobs:
       - name: Run data collection script
         run: python "data collection/energy_weather_data.py"
 
-      - name: Track updated CSV with DVC
+      - name: Track updated CSV and metrics.json with DVC
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
@@ -45,12 +45,19 @@ jobs:
         run: |
           dvc add data/uk_energy_data.csv
           git add data/uk_energy_data.csv.dvc .gitignore
+          # --- NEW: Add monitoring metrics if exists ---
+          if [ -f "monitoring/metrics.json" ]; then
+            git add monitoring/metrics.json
+            echo "✅ metrics.json added for commit"
+          else
+            echo "⚠️ metrics.json not found — skipping"
+          fi
 
       - name: Commit and push DVC changes to GitHub
         run: |
           git config --global user.name "github-actions"
           git config --global user.email "actions@github.com"
-          git commit -m "Update uk_energy_data.csv [auto data collection]" || echo "No changes to commit"
+          git commit -m "Update data & metrics [auto data collection]" || echo "No changes to commit"
           git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main
 
       - name: Push data to S3 using DVC
